version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    command: ['npm', 'run', 'start:dev']
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    user: '${UID}:${GID}'
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  minio:
    image: docker.io/bitnami/minio:2023
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
      - MINIO_DEFAULT_BUCKETS=${AWS_BUCKET_NAME}
      - MINIO_REGION_NAME=sa-east-1

volumes:
  postgres-data:
    name: postgres-data

  minio_data:
    driver: local
